In [1]:
import pandas as pd 
import numpy as np 
import torch 
import torch.nn as  nn
from sklearn.model_selection import train_test_split

In [2]:
X=torch.tensor([[4311,3123,1233],[4144,1335,6134]],requires_grad=True,dtype=torch.float32)
y=torch.tensor([[0.1,0.2,0.3]])

In [3]:
w=torch.tensor([1,1,1],requires_grad=True,dtype=torch.float32)
b=torch.tensor(0.0,requires_grad=True)

In [21]:
z=w*X+b 
z

tensor([[4311., 3123., 1233.],
        [4144., 1335., 6134.]], grad_fn=<AddBackward0>)

In [22]:
p=torch.sin(z)
p 

tensor([[ 0.6705,  0.2541,  0.9972],
        [-0.2370,  0.1760,  0.9992]], grad_fn=<SinBackward0>)

In [23]:
sigmoid=nn.Sigmoid()
values=sigmoid(p)
values 

tensor([[0.6616, 0.5632, 0.7305],
        [0.4410, 0.5439, 0.7309]], grad_fn=<SigmoidBackward0>)

In [24]:
loss=nn.MSELoss()
loss_v=loss(values,y)
loss_v 

C:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\nn\modules\loss.py:610: UserWarning: Using a target size (torch.Size([1, 3])) that is different to the input size (torch.Size([2, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor(0.1755, grad_fn=<MseLossBackward0>)

In [25]:
loss_v.backward()

In [26]:
w.grad

tensor([ 42.4602, 105.1742,  -8.7503])

In [27]:
b.grad

tensor(0.0113)

In [28]:
X.grad 

tensor([[ 0.0311,  0.0288,  0.0021],
        [-0.0272, -0.0280, -0.0011]])

In [29]:
X.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
w.grad.zero_() 

tensor([0., 0., 0.])