In [109]:
import torch

In [110]:
x=torch.tensor(3.0,requires_grad=True)

In [111]:
x

tensor(3., requires_grad=True)

In [112]:
y=x**3+2*x**2+x
y

tensor(48., grad_fn=<AddBackward0>)

In [113]:
y.backward(retain_graph=True)

In [114]:
x.grad

tensor(40.)

In [115]:
x1=torch.tensor(10.,requires_grad=True)
x1

tensor(10., requires_grad=True)

In [116]:
y1=3*x1**3+2*x1**2+x1
y1

tensor(3210., grad_fn=<AddBackward0>)

In [117]:
z1=torch.sin(y1)
z1

tensor(-0.6501, grad_fn=<SinBackward0>)

In [118]:
k1=torch.cos(z1)
k1

tensor(0.7960, grad_fn=<CosBackward0>)

In [119]:
m1=torch.arcsin(k1)
m1

tensor(0.9207, grad_fn=<AsinBackward0>)

In [120]:
n1=torch.log(m1)+1
n1

tensor(0.9174, grad_fn=<AddBackward0>)

In [121]:
n1.backward(retain_graph=True)

In [122]:
x1.grad

tensor(776.6058)

In [123]:
x=torch.tensor([1, 2,3, 4, 5, 6, 7, 8, 9, 10],dtype=torch.float32,requires_grad=True)
w=torch.ones_like(x,dtype=torch.float64,requires_grad=True)
b=torch.tensor(0,dtype=torch.float64,requires_grad=True)

In [124]:
y = torch.tensor([1, 0, 1, 1, 0, 0, 1, 0, 1, 0],dtype=torch.float32)

# Model predictions (intentionally BAD at edges)
y_pred = torch.tensor([0.99, 0.01, 1.0, 0.8, 0.0, 0.2, 0.95, 0.05, 0.999999, 0.000001],dtype=torch.float32)


In [125]:
y

tensor([1., 0., 1., 1., 0., 0., 1., 0., 1., 0.])

In [126]:
y_pred

tensor([9.9000e-01, 1.0000e-02, 1.0000e+00, 8.0000e-01, 0.0000e+00, 2.0000e-01,
        9.5000e-01, 5.0000e-02, 1.0000e+00, 1.0000e-06])

In [127]:
def cross_entropy_loss(actual,pred):
  pred=pred.double()
  eps=1e-15
  pred=torch.clamp(pred,eps,1-eps)
  loss = (-(actual * torch.log(pred) + (1 - actual) * torch.log(1 - pred))).mean()
  return loss

In [128]:
li=cross_entropy_loss(y,y_pred)
li

tensor(0.0569, dtype=torch.float64)

In [129]:
li.mean()

tensor(0.0569, dtype=torch.float64)

In [130]:
w

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64,
       requires_grad=True)

In [131]:
b

tensor(0., dtype=torch.float64, requires_grad=True)

In [132]:
z=w*x+b
z

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [133]:
sig=torch.sigmoid(z)
sig

tensor([0.7311, 0.8808, 0.9526, 0.9820, 0.9933, 0.9975, 0.9991, 0.9997, 0.9999,
        1.0000], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [134]:
loss=cross_entropy_loss(y,sig)
loss

tensor(3.1518, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [153]:
loss.backward(retain_graph=True)

In [154]:
x.grad

tensor([-2.6894e-02,  8.8080e-02, -4.7426e-03, -1.7986e-03,  9.9331e-02,
         9.9753e-02, -9.1105e-05,  9.9966e-02, -1.2339e-05,  9.9995e-02])

In [155]:
w.grad

tensor([-2.6894e-02,  1.7616e-01, -1.4228e-02, -7.1945e-03,  4.9665e-01,
         5.9852e-01, -6.3774e-04,  7.9973e-01, -1.1106e-04,  9.9995e-01],
       dtype=torch.float64)

In [156]:
b.grad

tensor(0.4536, dtype=torch.float64)

In [157]:
x.grad.zero_()
w.grad.zero_()
b.grad.zero_()

tensor(0., dtype=torch.float64)

In [158]:
#Using detach(),no_grad() and requires_grad_()

In [160]:
p=torch.detach(x)
p

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [174]:
y=(p**2).mean()
y

tensor(38.5000)

In [175]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [169]:
y=(x**2).mean()
y

tensor(38.5000, grad_fn=<MeanBackward0>)

In [171]:
y.backward()

In [172]:
x.grad

tensor([0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000, 1.8000,
        2.0000])

**#Using .no_grad()**

In [177]:
with torch.no_grad():
  y=(x**2).mean()

In [178]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Using .requires_grad_(False)**

In [180]:
x=x.requires_grad_(False)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [182]:
y=(x**2).mean()
y

tensor(38.5000)

In [183]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn