In [4]:
import torch
import numpy as np

In [5]:
import torch
torch.__version__

'2.10.0+cpu'

In [6]:
if torch.cuda.is_available():
  print('GPU')
  print(torch.cuda.get_device_name())
else:
  print("CPU")

CPU


In [7]:
# Using empty function

In [8]:
b=torch.empty(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
a=np.array([[1,2,3],[4,5,6]])
a.shape


(2, 3)

In [10]:
b=b+a

/tmp/ipykernel_3587/1259273152.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  b=b+a


In [11]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [12]:
type(b)

torch.Tensor

In [13]:
# Using zeros


In [14]:
c=torch.zeros(2,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
c=c+b
c

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [16]:
d=torch.ones(2,3)
d

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
d=d+c
d

tensor([[2., 3., 4.],
        [5., 6., 7.]], dtype=torch.float64)

In [18]:
torch.manual_seed(32)
torch.rand(2,3)


tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793]])

In [19]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [20]:
torch.arange(2,10,1)

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.arange(20,100,5)

tensor([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [22]:
torch.linspace(1,100,100)

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100.])

In [23]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
p=torch.full((2,3),5)
p

tensor([[5, 5, 5],
        [5, 5, 5]])

In [25]:
torch.manual_seed(12)
v=torch.rand_like(p,dtype=torch.float32)


In [26]:
v

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

In [27]:
torch.sum(v,dim=0)

tensor([1.0528, 0.6414, 0.5799])

In [28]:
torch.sum(v,dim=1)

tensor([1.1512, 1.1229])

In [29]:
r=torch.randint(10,30,(5,6))
r

tensor([[29, 13, 18, 10, 24, 23],
        [22, 15, 19, 11, 12, 17],
        [28, 28, 22, 19, 22, 14],
        [27, 28, 27, 21, 28, 26],
        [29, 15, 12, 29, 17, 10]])

In [30]:
torch.transpose(r,0,1)

tensor([[29, 22, 28, 27, 29],
        [13, 15, 28, 28, 15],
        [18, 19, 22, 27, 12],
        [10, 11, 19, 21, 29],
        [24, 12, 22, 28, 17],
        [23, 17, 14, 26, 10]])

In [31]:
torch.transpose(r,1,0)

tensor([[29, 22, 28, 27, 29],
        [13, 15, 28, 28, 15],
        [18, 19, 22, 27, 12],
        [10, 11, 19, 21, 29],
        [24, 12, 22, 28, 17],
        [23, 17, 14, 26, 10]])

In [32]:
b


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [33]:
torch.softmax(b,dim=0)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]], dtype=torch.float64)

In [34]:
print(b)
print(v)
b+v


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])


tensor([[1.4657, 2.2328, 3.4527],
        [4.5871, 5.4086, 6.1272]], dtype=torch.float64)

In [35]:
#Inplace Operations


In [36]:
b.add_(v)

tensor([[1.4657, 2.2328, 3.4527],
        [4.5871, 5.4086, 6.1272]], dtype=torch.float64)

In [37]:
b

tensor([[1.4657, 2.2328, 3.4527],
        [4.5871, 5.4086, 6.1272]], dtype=torch.float64)

In [38]:
#Tensor Operation On GPU

In [39]:
device=torch.device('cuda')
device

device(type='cuda')

In [40]:
j=torch.ones_like(v,device=device)
j

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
j+b.to(device)

In [ ]:
d

In [ ]:
c

In [ ]:
import time

In [ ]:
d1=torch.ones(30,30,dtype=torch.float32)
d1

In [ ]:
p1=torch.full((30,30),5,dtype=torch.float32)
p1

In [ ]:
start=time.time()
torch.matmul(p1,d1)
end=time.time()
print(start,end)
t=end-start
print('Total time on CPU.',t)

In [ ]:
d1=d1.to(device)
p1=p1.to(device)
start=time.time()
torch.matmul(p1,d1)
end=time.time()
print(start,end)
t2=end-start
print('Total time on CPU.',t2)

In [ ]:
t/t2

In [ ]:
d1.flatten()

In [ ]:
#NUMPY arrays and PyTorch

In [41]:
a=torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [42]:
b=np.array(a)
b


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
c=torch.tensor(b)
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
d=c.unsqueeze(0)
d

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [53]:
print(d.squeeze(0))

tensor([[1, 2, 3],
        [4, 5, 6]])
