In [1]:
import torch  

In [2]:
print(torch.__version__)

2.7.0+cpu


In [3]:
if torch.cuda.is_available(): 
    print('GPU Available')
    print(torch.cuda.get_device_name(0))

else: 
    print('No GPU available')

No GPU available


# Creating Tensor 

In [4]:
# Using empty 
p=torch.empty(3,4)
p 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
type(p)

torch.Tensor

In [6]:
# Using zeros 
q=torch.zeros(5,6)
q 

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

# Using Manual Seed 

In [7]:
torch.manual_seed(42)
r=torch.rand(3,4)
r 

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

# Using Tensor function 


In [121]:

s=torch.tensor(r.clone())
s 

C:\Users\hp\AppData\Local\Temp\ipykernel_8364\1072270892.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s=torch.tensor(r.clone())


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

# Using arange 

In [9]:
a=torch.arange(0,5,1)
a 

tensor([0, 1, 2, 3, 4])

# Using Linspace 

In [10]:
b=torch.linspace(0,0.1,10)
b 

tensor([0.0000, 0.0111, 0.0222, 0.0333, 0.0444, 0.0556, 0.0667, 0.0778, 0.0889,
        0.1000])

# USing eye function 

# Identity Matrix 

In [11]:
c=torch.eye(10)
c

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Using full 


In [12]:
f=torch.full((5,3),3)
f 

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

In [13]:
f.shape

torch.Size([5, 3])

In [14]:
g=torch.empty_like(f)
g 

tensor([[5766211897024,             0,             0],
        [            0,             0,             0],
        [            0,             0,             0],
        [            0,             0,             0],
        [            0,             0,             0]])

In [15]:
g.dtype

torch.int64

In [16]:
h=torch.rand_like(g,dtype=torch.float64)
(h) 

tensor([[0.9552, 0.9288, 0.0835],
        [0.1326, 0.1571, 0.3754],
        [0.8425, 0.8705, 0.3775],
        [0.6124, 0.0881, 0.7012],
        [0.6234, 0.4373, 0.0747]], dtype=torch.float64)

# Tensor Data Types 

In [17]:
ten=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int32)
ten

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [18]:
ten.type()

'torch.IntTensor'

In [19]:
ten.dtype

torch.int32

In [20]:
ten2=ten.to(torch.float64)
ten2

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Tensors OPeration 

In [21]:
ten2+ten 

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)

In [22]:
ten2-ten 

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [23]:
ten2*ten

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], dtype=torch.float64)

In [24]:
ten2 % ten 

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [25]:
ten % ten2 

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [26]:
ten2 ** ten 

tensor([[1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04]], dtype=torch.float64)

In [27]:
torch.sum(ten2)

tensor(21., dtype=torch.float64)

In [28]:
ten2 

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [29]:
torch.sum(ten2,dim=1)

tensor([ 6., 15.], dtype=torch.float64)

In [30]:
torch.sum(ten2,dim=0)

tensor([5., 7., 9.], dtype=torch.float64)

In [31]:
torch.mean(ten2,dim=1)

tensor([2., 5.], dtype=torch.float64)

In [32]:
tens=torch.tensor([[1,2,3],[4,5,6]])
tens 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
torch.sum(tens,dim=0)

tensor([5, 7, 9])

In [34]:
torch.sum(tens,dim=1)

tensor([ 6, 15])

In [35]:
torch.prod(tens)

tensor(720)

In [36]:
torch.max(tens)

tensor(6)

In [37]:
torch.min(tens)

tensor(1)

In [38]:
torch.prod(tens)

tensor(720)

In [39]:
torch.manual_seed(99)
tens2=torch.rand((2,3),dtype=torch.float64)
tens2 

tensor([[0.8265, 0.5846, 0.6141],
        [0.4022, 0.8863, 0.3845]], dtype=torch.float64)

In [40]:
torch.var(tens2)

tensor(0.0435, dtype=torch.float64)

In [41]:
torch.std(tens2)

tensor(0.2087, dtype=torch.float64)

In [42]:
torch.prod(tens2)

tensor(0.0407, dtype=torch.float64)

In [43]:
torch.argmax(tens2)

tensor(4)

# Matrix Multiplication 

In [44]:
x=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
y=torch.rand((3,4),dtype=torch.float32)


In [45]:
torch.matmul(x,y)

tensor([[ 1.5936,  3.2258,  2.9660,  4.6057],
        [ 4.1706,  9.2363,  8.5876, 10.8095]])

In [46]:
torch.linalg.matrix_rank(x)

tensor(2)

In [47]:
torch.matrix_power(torch.tensor([[1,2],[3,4]]),4)

tensor([[199, 290],
        [435, 634]])

In [48]:
d2=torch.tensor([1,2])
d1=torch.tensor([3,4])

In [49]:
torch.dot(d1,d2)

tensor(11)

# Transposing the Matrix 

In [50]:
tens 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
torch.transpose(tens,0,1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [52]:
torch.transpose(tens,1,0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [53]:
d1 

tensor([3, 4])

In [54]:
d2 

tensor([1, 2])

In [55]:
torch.greater(d1,d2)

tensor([True, True])

# Applying Functions  

In [56]:
torch.log(d1)

tensor([1.0986, 1.3863])

In [57]:
torch.exp(d1)

tensor([20.0855, 54.5981])

In [58]:
torch.sigmoid(d1)

tensor([0.9526, 0.9820])

In [59]:
tens.dtype

torch.int64

In [60]:
tens2.dtype

torch.float64

In [61]:
tens2

tensor([[0.8265, 0.5846, 0.6141],
        [0.4022, 0.8863, 0.3845]], dtype=torch.float64)

In [62]:
torch.softmax(tens2,dim=0)

tensor([[0.6045, 0.4251, 0.5572],
        [0.3955, 0.5749, 0.4428]], dtype=torch.float64)

In [63]:
torch.softmax(tens2,dim=1)

tensor([[0.3855, 0.3027, 0.3118],
        [0.2774, 0.4501, 0.2725]], dtype=torch.float64)

In [64]:
torch.relu(tens2)

tensor([[0.8265, 0.5846, 0.6141],
        [0.4022, 0.8863, 0.3845]], dtype=torch.float64)

In [66]:
tens3=torch.arange(0,10,2)
tens3

tensor([0, 2, 4, 6, 8])

In [67]:
torch.argmin(tens3)

tensor(0)

In [68]:
torch.argmax(tens3)

tensor(4)

In [74]:

vec1=torch.tensor([0.5615, 0.1774, 0.8147, 0.3295])
vec2=torch.tensor([0.2319, 0.7832, 0.8544, 0.1012])


In [75]:
torch.dot(vec1,vec2)

tensor(0.9986)

In [84]:
trans=torch.rand(7,6)

In [85]:
trans

tensor([[0.2351, 0.7374, 0.4900, 0.2658, 0.1319, 0.9753],
        [0.2768, 0.7972, 0.7241, 0.1374, 0.4890, 0.0219],
        [0.4910, 0.8329, 0.4745, 0.0152, 0.7072, 0.5548],
        [0.5564, 0.5547, 0.0799, 0.0740, 0.0415, 0.9209],
        [0.0537, 0.1704, 0.3770, 0.6058, 0.1223, 0.1785],
        [0.4108, 0.6423, 0.0363, 0.9581, 0.9809, 0.2205],
        [0.6127, 0.0299, 0.3441, 0.2502, 0.8165, 0.6867]])

In [86]:
torch.transpose(trans,0,1)

tensor([[0.2351, 0.2768, 0.4910, 0.5564, 0.0537, 0.4108, 0.6127],
        [0.7374, 0.7972, 0.8329, 0.5547, 0.1704, 0.6423, 0.0299],
        [0.4900, 0.7241, 0.4745, 0.0799, 0.3770, 0.0363, 0.3441],
        [0.2658, 0.1374, 0.0152, 0.0740, 0.6058, 0.9581, 0.2502],
        [0.1319, 0.4890, 0.7072, 0.0415, 0.1223, 0.9809, 0.8165],
        [0.9753, 0.0219, 0.5548, 0.9209, 0.1785, 0.2205, 0.6867]])

In [87]:
torch.transpose(trans,1,0)

tensor([[0.2351, 0.2768, 0.4910, 0.5564, 0.0537, 0.4108, 0.6127],
        [0.7374, 0.7972, 0.8329, 0.5547, 0.1704, 0.6423, 0.0299],
        [0.4900, 0.7241, 0.4745, 0.0799, 0.3770, 0.0363, 0.3441],
        [0.2658, 0.1374, 0.0152, 0.0740, 0.6058, 0.9581, 0.2502],
        [0.1319, 0.4890, 0.7072, 0.0415, 0.1223, 0.9809, 0.8165],
        [0.9753, 0.0219, 0.5548, 0.9209, 0.1785, 0.2205, 0.6867]])

In [91]:
tens5 = torch.tensor([[[[[1.,2.,3.,4.,5.],
                         [6.,7.,8.,9.,10.],
                         [11.,12.,13.,14.,15.],
                         [16.,17.,18.,19.,20.]]]]])
tens5

tensor([[[[[ 1.,  2.,  3.,  4.,  5.],
           [ 6.,  7.,  8.,  9., 10.],
           [11., 12., 13., 14., 15.],
           [16., 17., 18., 19., 20.]]]]])

In [90]:
torch.transpose(tens5,0,1)

tensor([[[[[ 1.,  2.,  3.,  4.,  5.],
           [ 6.,  7.,  8.,  9., 10.],
           [11., 12., 13., 14., 15.],
           [16., 17., 18., 19., 20.]]]]])

In [89]:
torch.transpose(tens5,1,0)

tensor([[[[[ 1.,  2.,  3.,  4.,  5.],
           [ 6.,  7.,  8.,  9., 10.],
           [11., 12., 13., 14., 15.],
           [16., 17., 18., 19., 20.]]]]])

# Inplace Operations 

In [97]:
torch.manual_seed(20)
t1=torch.rand(2,3)
t2=torch.rand(2,3)

In [98]:
t1 

tensor([[0.5615, 0.1774, 0.8147],
        [0.3295, 0.2319, 0.7832]])

In [99]:
t2 

tensor([[0.8544, 0.1012, 0.1877],
        [0.9310, 0.0899, 0.3156]])

# For Memory Efficieny


In [102]:
t1.add_(t2)

tensor([[1.4159, 0.2786, 1.0024],
        [1.2606, 0.3218, 1.0988]])

In [103]:
t1

tensor([[1.4159, 0.2786, 1.0024],
        [1.2606, 0.3218, 1.0988]])

In [104]:
t1.relu_()

tensor([[1.4159, 0.2786, 1.0024],
        [1.2606, 0.3218, 1.0988]])

# USing Clone Function 

In [107]:
t1 

tensor([[1.4159, 0.2786, 1.0024],
        [1.2606, 0.3218, 1.0988]])

In [105]:
x=t1 

In [106]:
x 

tensor([[1.4159, 0.2786, 1.0024],
        [1.2606, 0.3218, 1.0988]])

In [108]:
t1[0][1]=-4.5

In [109]:
t1 

tensor([[ 1.4159, -4.5000,  1.0024],
        [ 1.2606,  0.3218,  1.0988]])

In [110]:
x

tensor([[ 1.4159, -4.5000,  1.0024],
        [ 1.2606,  0.3218,  1.0988]])

In [112]:
id(t1)

1963159187008

In [114]:
id(x)

1963159187008

In [115]:
y=t1.clone()
y

tensor([[ 1.4159, -4.5000,  1.0024],
        [ 1.2606,  0.3218,  1.0988]])

In [116]:
t1[0][0]=-1
t1

tensor([[-1.0000, -4.5000,  1.0024],
        [ 1.2606,  0.3218,  1.0988]])

In [117]:
x 

tensor([[-1.0000, -4.5000,  1.0024],
        [ 1.2606,  0.3218,  1.0988]])

In [118]:
y 

tensor([[ 1.4159, -4.5000,  1.0024],
        [ 1.2606,  0.3218,  1.0988]])

In [120]:
id(y),id(x),id(t1)

(1963202117488, 1963159187008, 1963159187008)